name: MAIN

# Run on push only for main
# Otherwise it may trigger concurrently `push & pull_request` on PRs.
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.vscode/**'
      - 'docs/**'
      - 'examples/**'
      - 'LICENSE'
      - 'tools/**'
      - 'graphs/**'
  pull_request:
    paths-ignore:
      - '*.md'
      - '.vscode/**'
      - 'docs/**'
      - 'examples/**'
      - 'LICENSE'
      - 'tools/**'
      - 'graphs/**'
  workflow_dispatch:

jobs:
  #
  # Development Verification
  #
  development:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Code 🚪
        uses: actions/checkout@v2

      - name: Setup Node ⚙️
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Cache Node Modules 🛢️
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Cache Cypress Binary 🛢️
        id: cache-cypress-binary
        uses: actions/cache@v2
        with:
          path: cypress/cache
          key: cypress-binary-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies 🔧
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Get branch name
        id: branch
        run: echo ::set-output name=current_branch::${GITHUB_REF#refs/*/}

      - name: Prisma generate
        run: yarn prisma:avidtrader-api:generate

      - name: Run linter
        run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn lint:ci

      - name: Run builder
        run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn build:ci

      - name: Run tester
        run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn test:ci

      - name: Run e2e
        run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn e2e:ci

      - name: Combine coverage
        run: |
          NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn coverage:merge

      - name: Push coverage to coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './coverage/lcov.combo.info'
